language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5
cache: pip
install:
- pip install pytest pytest-cov coveralls flake8
- pip install futures
- |
  if python -c 'import sys; sys.exit(1 if sys.hexversion<0x03000000 else 0)'
  then
    pip install pytest-asyncio
  fi
- pip install -e .
script:
- py.test --cov=promise tests
after_success:
- coveralls
matrix:
  fast_finish: true
  include:
  - python: '2.7'
    script: flake8
  - python: '3.5'
    script: |
      pip install mypy-lang
      mypy promise/
